### ISSUE TITLE
Add seminars to onboarding doc

### ISSUE THREAD

**Issue by SarahFriedman-NOAA** [afsc-gap-products/general#1]
We need a way to communicate the different science seminars, etc. that are available to NOAA employees that may want to be more involved. Perhaps a curated list of talks, seminar series, and the like?

**Comment by Lewis-Barnett-NOAA** [comment]
bumpity bump bump, FYI folks, we made a general GitHub repository for cataloging and solving all kinds of "to do" items or gathering little gems of good ideas or essential documentation that pops up along the way.

**Comment by MargaretSiple-NOAA** [comment]
Just added each of the regional teams as collaborators on this repo (I think that means they'll get notifications when there's a new issue). All have write access. I think this is a good idea.

**Comment by Lewis-Barnett-NOAA** [comment]
There is a link on the AFSC intranet that is well hidden, but will add AFSC events to one's google calendar.  I only just found out about this, so I added it to our onboarding Google Doc.
