### ISSUE TITLE
Interesting books, movies and shows during travel/at sea?

### ISSUE THREAD

**Issue by Lewis-Barnett-NOAA** [afsc-gap-products/general#2]
We all have exhausted all forms of entertainment during the pandemic, so let's hear some recommendations for good reading/watching materials for the survey.  I'll start us off:

**Film**:

Aleutian Islanders, watch "Village of the Damned" as it was filmed in/around the area I grew up and it is the kind of dystopian film that would be good to watch on Adak I bet: http://www.thennowmovielocations.com/2018/01/village-of-damned-1995.html

**Literature**:

FLOATING COAST
An Environmental History of the Bering Strait
By Bathsheba Demuth
Review: https://www.nytimes.com/2019/08/27/books/review/floating-coast-bathsheba-demuth.html

Soonish: Ten Emerging Technologies That'll Improve and/or Ruin Everything
https://www.goodreads.com/book/show/34490192-soonish

**Comment by MargaretSiple-NOAA** [comment]
BOOK TALK! My favorite topic! Jim also recommended Floating Coast to me.

These are the books I packed in my sea bag. 
<img src="https://user-images.githubusercontent.com/73858992/167960023-9c549b5c-0b92-4dc8-a58f-44af8b2842e2.jpg" alt="drawing" width="300"/>

**Comment by StanKotwicki-NOAA** [comment]
I recommend:
[Ada Blackjack: A True Story of Survival in the Arctic](https://www.amazon.com/Ada-Blackjack-Story-Survival-Arctic/dp/078688746X/ref=sr_1_1?keywords=ada+blackjack+book&qid=1652311838&s=books&sprefix=ada+the+bla%2Cstripbooks%2C127&sr=1-1)
by [Jennifer Niven](https://www.amazon.com/Jennifer-Niven/e/B001KHAA4S?ref=sr_ntt_srch_lnk_1&qid=1652311838&sr=1-1)

**Comment by coleary-noaa** [comment]
['Braiding Sweetgrass' ](https://www.google.com/search?q=braiding+sweetgrass&rlz=1C1GCEA_enUS847US847&oq=braiding+s&aqs=chrome.0.0i355i433i512j46i433i512j69i57j0i512l7.1857j0j7&sourceid=chrome&ie=UTF-8) by Robin Wall Kimmerer
